language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  # install composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
