<?php
namespace Dotapi2\Tests\Entity;

class MatchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Dotapi2\Entity\Match
     */
    protected $entity;


    protected $data;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $entityFactory = new \Dotapi2\Entity\EntityFactory();
        $matchData = json_decode(file_get_contents('./tests/Responses/getMatchHistory.json'), true);
        $this->data = $matchData['result']['matches'][0];
        $this->entity = $entityFactory->create('Match', $this->data);
    }

    public function testGetId()
    {
        $this->assertEquals($this->data['match_id'], $this->entity->getId());
    }

    public function testGetPlayers()
    {
        $this->assertInstanceOf('\Dotapi2\Collection\Slot', $this->entity->getPlayers());
    }

    public function testGetSequenceNumber()
    {
        $this->assertEquals($this->data['match_seq_num'], $this->entity->getSequenceNumber());
    }

    public function testGetStartTime()
    {
        $this->assertEquals($this->data['start_time'], $this->entity->getStartTime()->getTimestamp());
    }

    public function testGetLobbyType()
    {
        $this->assertEquals($this->data['lobby_type'], $this->entity->getLobbyType());
    }

}

